services:
  nginx:
    image: nginx
    container_name: web
    restart: always
    ports:
      - 80:80

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TestApi
    ports:
      - 5432

  adminer:
    image: adminer
    container_name: db-ihm
    restart: always
    ports:
      - 8080:8080